# This workflow will build a Java project with Maven and then deploys it to Heroku using Docker
# For more information see:
#  - https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app

name: CI/CD

on:
  push:
    branches: [ main, macro-merge ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      - name: Test and build
        run: |
          docker run -d -p 8080:8080 udlepssoftarch/linkapp-api
          while ! nc -z localhost 8080; do sleep 10; done
          docker ps -a
          npm ci
          npm run lint
          npx start-server-and-test start http-get://localhost:4200 'cypress run --record --key ${{ secrets.CYPRESS_KEY }}'
          npm run build -- --configuration production
      - name: Build Dock er image and deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: jctaveras/heroku-deploy@v2.1.1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: 'link--app'
          dockerfile_path: ''
